<?php
/**
 * @file
 * Code for the Listing View feature.
 */

include_once 'listing_view.features.inc';


/*
 * Get the child nodes of a menu item
 */
function listing_view_get_child_nids() {
  $selected_menu = NULL;
  $parent = menu_link_get_preferred(NULL, $selected_menu);
  $parameters = array(
    'active_trail' => array($parent['plid']),
    'only_active_trail' => FALSE,
    'min_depth' => $parent['depth']+1,
    'max_depth' => $parent['depth']+1,
    'conditions' => array('plid' => $parent['mlid']),
  );
  
  $children = menu_build_tree($parent['menu_name'], $parameters);
  
  $nids = array();
  if (!empty($children)) {
    foreach($children as $child) {
      $item = menu_get_item($child['link']['link_path']);
      if ($item['map'][0] == 'node' && !empty($item['map'][1]->nid)) {
        $nids[$item['map'][1]->nid] = $item['map'][1]->nid;
      }
    }
  }
  
  return implode(',', $nids);
}